version: "3"
networks:
  dem:
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - .devops/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - dem
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root 
    ports: 
      - "5000:80"
    depends_on:
      - db
    networks:
      - dem
  backend:
    build: .
    command: ["sleep", "3600000"]
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dem
